import { FORMS } from '../../scripts/constants';

export const DATABASE_KEYS = Object.freeze({
  USERS: 'users',
  ANSWER: 'answer',
  ATTITUDE: 'attitude',
  INTERPERSONAL_RELATIONSHIP: 'interpersonal_relationship',
  EMOTIONAL_REGULATION: 'emotional_regulation',
  // Only when form is in progress
  TEMP_ATTITUDE: 'temp_attitude',
  TEMP_INTERPERSONAL_RELATIONSHIP: 'temp_interpersonal_relationship',
  TEMP_EMOTIONAL_REGULATION: 'temp_emotional_regulation',
});

export const FORM_MAPPER = Object.freeze({
  [FORMS.ATTITUDE]: DATABASE_KEYS.ATTITUDE,
  [FORMS.INTERPERSONAL_RELATIONSHIP]: DATABASE_KEYS.INTERPERSONAL_RELATIONSHIP,
  [FORMS.EMOTIONAL_REGULATION]: DATABASE_KEYS.EMOTIONAL_REGULATION,
});

export const CONVERT_DATABASE_KEY_TO_FORM = Object.freeze({
  [DATABASE_KEYS.ATTITUDE]: FORMS.ATTITUDE,
  [DATABASE_KEYS.INTERPERSONAL_RELATIONSHIP]: FORMS.INTERPERSONAL_RELATIONSHIP,
  [DATABASE_KEYS.EMOTIONAL_REGULATION]: FORMS.EMOTIONAL_REGULATION,
});

export const TEMP_FORM_MAPPER = Object.freeze({
  [FORMS.ATTITUDE]: DATABASE_KEYS.TEMP_ATTITUDE,
  [FORMS.INTERPERSONAL_RELATIONSHIP]: DATABASE_KEYS.TEMP_INTERPERSONAL_RELATIONSHIP,
  [FORMS.EMOTIONAL_REGULATION]: DATABASE_KEYS.TEMP_EMOTIONAL_REGULATION,
});

export const CONVERT_TEMP_KEY_TO_PERMANENT_KEY_MAPPER = Object.freeze({
  [DATABASE_KEYS.TEMP_ATTITUDE]: DATABASE_KEYS.ATTITUDE,
  [DATABASE_KEYS.TEMP_INTERPERSONAL_RELATIONSHIP]: DATABASE_KEYS.INTERPERSONAL_RELATIONSHIP,
  [DATABASE_KEYS.TEMP_EMOTIONAL_REGULATION]: DATABASE_KEYS.EMOTIONAL_REGULATION,
});
